module Api::V1::MsgConstants
	MISSING_PARAMS_MSG = "missing_params"
	SUCCESSFULLY_SENT_MSG = "Successfully Sent"
	PASSWORD_VALIDATION_MSG = "Password should be match and password's length should be greater than 6"
	PERSON_TYPE_VALIDATION_MSG = "Type should be in Listener , Artist or Manager"
	REGISTRATION_SUCCESS_MSG = "Successfull Registered"
	REGISTRATION_FAIL_MSG = "Something went wrong"
	LOGIN_SUCCESS_MSG =  "Successfull Login"
	EMAIL_VALID_MSG = "Email is valid"
	EMAIL_INVALID_MSG = "Email already used"
	LOGOUT_SUCCESS_MSG = "Successfully log out!"
	USER_NOT_FOUND_MSG = "User not found"
	PASSWORD_INVALID_MSG = "Password doesn't matched"
	SUCCESS_DEFAULT_MSG = "Success!!"
end