development:
  adapter: mysql2
  encoding: utf8
  database: s90_development
  username: root
  password: 123
  host: 127.0.0.1
  port: 3306

production:
  adapter: mysql2
  url: <%= ENV["DB_URI"] %>
  pool: 15